### ISSUE TITLE
As a Data/Web Manager I want to add a metadata record for the whole database so that data users can understand how the data are collated and cite it correctly

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#207]

**Comment by neil-ices-dk** [comment]
we would understand this is to be defined by users i.e. at survey level etc. not sure that the system needs to do anything specific here? @GMDuncan

**Comment by GMDuncan** [comment]
I think the idea behind this user story was to have a single parent metadata record describing the database as a whole, so that people could use it as a reference if they were talking about the system/database rather than an individual surveys.

However:

- Possibly worthwhile rechecking if this is required by the stakeholders
- If done it'd only need to be created once (i.e. for the single database), by either ICES or JNCC (not any standard users) on GeoNetwork
-  Hopefully little or no maintenance requirement depending on the level of detail in the record, but possibly a requirement to keep temporal and spatial extent updated at a determined frequency?
- Trying to think of a relevant metaata category for this. Not a dataset or a service really (unless you substitute this user story with one for the service?), so probably left with "Directory"?
- Agreed with "not sure that the system needs to do anything specific here?", if taken forward it really is just the creation of a standard metadata record on the existing GeoNetwork

**Comment by GMDuncan** [comment]
@LynnHeeley recheck if this is necessary with steering group.

**Comment by PeriklisICES** [comment]
I have created an overarching record for the database:
https://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/f7b9234a-8f9c-4db3-bcd3-898952b5cd9a (requires login)

This record needs to be edited accordingly. Need help from @NikiClear @NikkiTaylorJNCC 

I have also edited the template to associate any new record to the database record. As a result, if a record is not associated with the database (Are there going to be any?) then the association has to be removed by the user. Note that is not part of the INSPIRE fields so the view in editor has to be edited. If we think this is too complicated/prone to mistakes, I recommend creating a second template for datasets that are not going to be in the database.

Here is how the database record looks like:
![image](https://user-images.githubusercontent.com/19410420/151784876-92f89cc0-31b6-42cd-b984-382793a370b4.png)
Geonetwork identifies every record associated with the database and lists them. List will get longer and longer...

Here is how an individual record looks like:
![image](https://user-images.githubusercontent.com/19410420/151785265-743ed701-a05b-4d13-8404-49863fd69d45.png)

**Comment by neil-ices-dk** [comment]
> @PeriklisICES Some minor updates made to the metadata entry - I think it's looking good, thanks!

i'm thinking we should add a suggested citation to the landing page, along with a link to this meta record - agree?

**Comment by NikkiTaylorJNCC** [comment]
@neil-ices-dk @PeriklisICES Certainly need a link to the metadata record on the landing page and we'll find a suitable location to host it in the hub as well (@NikiClear) . Re citation... we have the acknowledgement guidance in the supplementary Data Provision, Access and Use Guidance, but not a JCDP citation. Is there an accepted format for other ICES databases that we could amend?

**Comment by neil-ices-dk** [comment]
@NikkiTaylorJNCC minimum citation example here https://www.ices.dk/data/data-portals/Pages/European-Seabirds-at-sea.aspx which we could place on the front page and then add the metadata link on the right hand menu

Extended citation guidance is provided in the data policy https://doi.org/10.17895/ices.pub.8883

**Comment by NikkiTaylorJNCC** [comment]
OK, I propose:
Joint Cetacean Data Programme (JCDP) (https://www.ices.dk/data/data-portals/Pages/Cetaceans.aspx), 2022. ICES, Copenhagen

**Comment by neil-ices-dk** [comment]
counter proposal 😉 

Joint Cetacean Data Programme (JCDP) (https://cetaceans.ices.dk), 2022. ICES, Copenhagen

**Comment by NikkiTaylorJNCC** [comment]
Show off :D  Perfect! Done deal.

**Comment by neil-ices-dk** [comment]
Citation now live;
@PeriklisICES will you publish the meta data record, i can then include that link

**Comment by PeriklisICES** [comment]
Apologies for the delay. It is now published.
