### ISSUE TITLE
Vocabularies vocab.ices.dk

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#223]
Platform (SHIPC) #219

**Comment by neil-ices-dk** [comment]
29 Sep, the vocab management group will discuss the setup of the cetaceans specific vocabs

**Comment by neil-ices-dk** [comment]
@pcrjoana to add a list (inc. URL) of new vocabs once they are setup

**Comment by neil-ices-dk** [comment]
[BD_Count](//vocab.ices.dk/?ref=1440) codes changed from characters to numbers to be consistent with existing code vocab; to be updated in data standard

**Comment by pcrjoana** [comment]
All the vocabularies have been inserted to the system and linked to the data format.
For a summary of which vocabularies are to be used in each field, please consult [datsu](http://datsu.ices.dk/web/selRep.aspx?Dataset=149).

**Comment by NikkiTaylorJNCC** [comment]
@pcrjoana just flagging there are still only 2 platform classes in the template: 54 airship and 3Z surface vessel - we agreed to remove airship and retain the original 'Aeroplane' and 'Unmanned aerial vehicle'

**Comment by pcrjoana** [comment]
Thank you Nikki! I changed this, but it probably got lost in the multiple template exchanges. I'll update it.

**Comment by pcrjoana** [comment]
Now that I'm looking at this again, I'm wondering if I forgot to save the changes...I'll also need to add the new/changed codes to behaviour.

**Comment by NikkiTaylorJNCC** [comment]
@pcrjoana the codes for targettaxa are also not the same as the data standard: standard is 'cetacean, multi taxa, secondary'; the template is currently 'multispecies' and 'cetaceans only'. These are incorrect...we need the codes as in standard...

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC In the datastandard v7 we have "cetacean", "multispecies", and "other". We agreed that "other" shouldn't be a code, and that new codes should be requested. 
Are we adding a "secondary" code? What is the description?

**Comment by NikkiTaylorJNCC** [comment]
> Now that I'm looking at this again, I'm wondering if I forgot to save the changes...I'll also need to add the new/changed codes to behaviour.

Can we also remove the commas from the survey id format in identifiers?

**Comment by pcrjoana** [comment]
> > Now that I'm looking at this again, I'm wondering if I forgot to save the changes...I'll also need to add the new/changed codes to behaviour.
> 
> Can we also remove the commas from the survey id format in identifiers?

I'm not sure I understand what you're asking.

Back to TargetTaxa, can "Cetaceans only" remain as it is? The reason for this is to avoid having redundant codes with the ESAS data.

**Comment by NikkiTaylorJNCC** [comment]
> @NikkiTaylorJNCC In the datastandard v7 we have "cetacean", "multispecies", and "other". We agreed that "other" shouldn't be a code, and that new codes should be requested. Are we adding a "secondary" code? What is the description?

'Cetaceans': Cetaceans (whales, dolphins, and porpoises) are the primary focus of the survey and observers/equipment are dedicating time on effort to detecting them. 
'Multi-taxa': Cetaceans (whales, dolphins, and porpoises) and other species (e.g. birds; turtles, sharks) are the primary focus of the survey. Although observers/equipment are searching for cetaceans at all times; search is also being carried out for other species which may impact the capacity to detect cetaceans 
'Secondary': Cetaceans (whales, dolphins and porpoises) are not the target taxa for the survey but may be recorded on an opportunistic basis. Search for cetaceans is not dedicated and may not be constant within a period of effort.

**Comment by NikkiTaylorJNCC** [comment]
> 

The trouble with 'cetaceans only' is that we aren't restricting it to cetaceans only...there may be other records on a cetacean survey, which is particularly common in citizen science surveys...(see definition)

**Comment by pcrjoana** [comment]
I'll bring this to the vocabulary management group. :-)

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC we just discussed this in the vocabulary management group. We will add "secondary" to TargetTaxa. Dropping the "only" in "cetaceans only" is something that needs to be approved by ESAS. We can probably include in the description that cetaceans are the main target, since our understanding is that a survey targeting only a group of species does not exclude other taxonomic groups being recorded on an opportunistic basis.

**Comment by pcrjoana** [comment]
Another thing @NikkiTaylorJNCC, the dedicated vs opportunistic survey is already covered in another field. Does this need to be mentioned again in TargetTaxa? It feels like we're mixing concepts here.

**Comment by NikkiTaylorJNCC** [comment]
> @NikkiTaylorJNCC we just discussed this in the vocabulary management group. We will add "secondary" to TargetTaxa. Dropping the "only" in "cetaceans only" is something that needs to be approved by ESAS. We can probably include in the description that cetaceans are the main target, since our understanding is that a survey targeting only a group of species does not exclude other taxonomic groups being recorded on an opportunistic basis.

OK, I just think having 'only' will be confusing and we are relying on people reading the full description.

**Comment by NikkiTaylorJNCC** [comment]
> Another thing @NikkiTaylorJNCC, the dedicated vs opportunistic survey is already covered in another field. Does this need to be mentioned again in TargetTaxa? It feels like we're mixing concepts here.

They are both needed - one refers to the focal taxa, the other refers to the nature of the platform.

**Comment by NikkiTaylorJNCC** [comment]
@pcrjoana - I have just gone through the data standard against the vocab tab in the template v I downloaded from the cetacean link on the landing page - so I may not have the latest template version. Some subsequent comments to consider, hopefully nothing too monumental! Shout if anything is unclear and if you can respond to the list to say what has happened, if anything, I can make sure the data standard doc is amended. •	Don't need code 19 - double platform line transect, under BD count method.

•	Target taxa - already discussed the three options needed (Cetacean; Multi-taxa; Secondary) with a pref to remove 'only' after 'cetacean' that currently exists. Multispecies could also be multitaxa instead if simple to change. If not, not a huge deal, I can amend the standard. 
•	Swell height - H needs to be very high 3+m and need an addition of H - high 2-3m
•	Glare missing from the template - vocab tab:  Not recorded; None; Slight; Moderate; Strong - is this missing because the vocab is the same as others? Think it still needs to be included in the vocab tab. 
•	PrecipIntentisy missing from template - vocab tab: Not recorded; Slight; Moderate; Strong. As above.
•	Visibility - 'not recorded' needs to be added as this is now a mandatory field.
•	CloudCover is missing 'not recorded' in the template vocab tab . E - description is a copy and paste error - needs to be 81-100%
•	Yes/No field - needs addition of 'possible'
•	Can 'sighting position' be renamed 'sighting direction'?

**Comment by neil-ices-dk** [comment]
Target taxa - remove 'only' in template vocab
In template #12 to label vocabs that are used for multiple fields appropriately so it is clear which ones are connected to each vocab 
- add JCDP name label above each vocab

> 	Yes/No field - needs addition of 'possible'
@pcrjoana to discuss with vocab governance group to establish a new vocab

vocab: will remain as 'sighting position'

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC the "Secondary" added to TargetTaxa is instead "Cetaceans as secondary target taxa", to keep consistency with the remaining codes in the vocabulary. The description in the template will be shortened to "Secondary", though.
