### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#233]
Users can now screen their files:

https://cetaceans.ices.dk/manage/ScreenFile

_Originally posted by @cmspinto in https://github.com/ices-tools-dev/cetaceans/issues/49#issuecomment-957909228_

**Comment by neil-ices-dk** [comment]
![image](https://user-images.githubusercontent.com/23527005/139945664-08fe4ab9-c662-43e3-a8ed-7057966dcfd1.png)
Can you rewrite this text
also the link to the password reset should be https://www.ices.dk/Pages/Password.aspx

**Comment by neil-ices-dk** [comment]
it is now possible to screen a file (pending the latest series of updates to format). We will put on website once the changes to the text and links have been made

**Comment by cmspinto** [comment]
Is it fine now [here](https://cetaceans.ices.dk/Account/Login?ReturnUrl=%2Fmanage):
![image](https://user-images.githubusercontent.com/8705477/140314653-e19b8e70-166b-4431-b9ef-a35271d0a10d.png)

**Comment by neil-ices-dk** [comment]
![image](https://user-images.githubusercontent.com/23527005/140373696-f5b80203-d3b5-4354-91ae-47785ad4d19b.png)

**Comment by NikiClear** [comment]
I have come across some errors while using the file screen tool with SCANS pilot data, which don't appear to be because of the data format. 
 
- **AphiaID** not accepting some entries. 'Lagenorhynchus albirostris', 'Globicephala melas', 'Delphinidae' and 'Balaenoptera acutorostrata' aren't in the vocab list http://vocab.ices.dk/?ref=365 (these are examples I found, there may be others)
- **DuplicateSightingStatus** field not accepting 'No'. Getting both 'Field value is invalid (Rel) - prevents entry to database' and 'Field width exceeded expected maximum' errors
- **CloudCover** will not accept 'Not recorded'. Getting both 'Field value is invalid (Rel) - prevents entry to database' and 'Field width exceeded expected maximum' errors

@pcrjoana @cmspinto @neil-ices-dk @NikkiTaylorJNCC

**Comment by neil-ices-dk** [comment]
sound like 🐛 bugs to me...

**Comment by pcrjoana** [comment]
> I have come across some errors while using the file screen tool with SCANS pilot data, which don't appear to be because of the data format.

There are some AphiaID missing in our vocab - I'll check which ones need to be added, and do that. :-)
> * **AphiaID** not accepting some entries. 'Lagenorhynchus albirostris', 'Globicephala melas', 'Delphinidae' and 'Balaenoptera acutorostrata' aren't in the vocab list http://vocab.ices.dk/?ref=365 (these are examples I found, there may be others)
@NikiClear I think you might be using the descriptions (i.e. "No", "Not recorded") instead of the vocabulary codes (N in both cases)?
> * **DuplicateSightingStatus** field not accepting 'No'. Getting both 'Field value is invalid (Rel) - prevents entry to database' and 'Field width exceeded expected maximum' errors
> * **CloudCover** will not accept 'Not recorded'. Getting both 'Field value is invalid (Rel) - prevents entry to database' and 'Field width exceeded expected maximum' error

**Comment by neil-ices-dk** [comment]
@pcrjoana to look at AphiaID's 03/12 @cmspinto to assist in adding by bulk

**Comment by neil-ices-dk** [comment]
@pcrjoana and @NikiClear can we close this issue (new validation requests should come on a new issue as needed)
