### ISSUE TITLE
testing of multiple file split in Excel template (v2)

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#246]
resulting from #240 survey instance discussion:
- need end user testing i.e. with @NikiClear and Lucy to validate this works

**Comment by NikiClear** [comment]
File screening page shows "Sorry, you are not allowed to upload this file to the database!" error while a file screening is being processed, this could be confusing to the user. 


I received the following errors during file screening; 

**error: Field width exceeded expected maximum	31: Research vessel	PlatformCode**
 I followed the same format as PlatformClass field, but received this error. I also tried with just the code (31) and stull received this error. What format should PlatformCode be? 

**error: Field width exceeded expected maximum	Secondary	PlatformInstance**
'Secondary' was selected from the dropdown list. Check whether script is changing this to '2' for sightings table?

**error: Field width exceeded expected maximum	Primary	PlatformInstance**
'Primary' was selected from the dropdown list. Check whether script is changing this to '1' for sightings table?

**error:  Field value is invalid (Rel) - prevents entry to database	125	Behaviour1**
'125 (Surfacing) was selected from the dropdown list, not sure what the issue is with this one.

**Comment by neil-ices-dk** [comment]
template was out of date, errors are resolved.
Niki used platform class instead of code, user error
- vocab for 'behaviour' was out of sync between template and actual vocab.ices.dk codeType
- @pcrjoana to update **version 2.03** of the template with the behaviour correction

**Comment by neil-ices-dk** [comment]
the split file has been tested, all fine
