### ISSUE TITLE
data submitters should be invited to test the download function; so they understand the process, and also get some trust in the way it works

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#267]
data submitters should be invited to test the download function; so they understand the process, and also get some trust in the way it works
@NikkiTaylorJNCC

_Originally posted by @neil-ices-dk in https://github.com/ices-tools-dev/cetaceans/issues/248#issuecomment-1149825781_

**Comment by neil-ices-dk** [comment]
@cmspinto  to clear down the download list so we are at ground zero

**Comment by NikiClear** [comment]
@neil-ices-dk @cmspinto @pcrjoana @NikkiTaylorJNCC 

### Reported issue from QC form: 

**Quality Control Check Proposed:**
The duplication appeared to be because there were 14 different identifiers so each effort record and sighting record were being extracted 14 times (i.e. once for each identifier). The filters I used were harbour porpoise, data from surface vessels and for the Greater North Sea and Celtic Sea. The data I got were all SCANS 2005 data, but due to 7 ships being used and each ship using 2 methodologies there were 14 identifiers. I think the relationship should be a one-to-many to extract the data properly, but instead it is a many-to-many relationship, resulting in duplication of data.

**Applicable to:**
["Identifiers record\n","Sightings record\n","Effort and Environment record\n"]

**Additional comments:**
I tried downloading some data and found that both effort and sightings records were duplicated 14 times, i.e. each effort segment was recorded 14 times and each sighting was recorded 14 times.

**Comment by cmspinto** [comment]
Would you have a Download ID I can use to extract the data and see the duplication?

**Comment by NikiClear** [comment]
> Would you have a Download ID I can use to extract the data and see the duplication?

https://cetaceans.ices.dk/Download/121c8af9-5914-419b-b843-d6e04a95d09c

**Comment by NikkiTaylorJNCC** [comment]
> data submitters should be invited to test the download function; so they understand the process, and also get some trust in the way it works @NikkiTaylorJNCC
> 
> _Originally posted by @neil-ices-dk in [#248 (comment)](https://github.com/ices-tools-dev/cetaceans/issues/248#issuecomment-1149825781)_

ORCA have been invited to test the download function and will test soon, feedback to come via the form.

**Comment by cmspinto** [comment]
Thanks for the heads up, this error was due to our change in the format. 
It was linking by the file instead of the identifier. 
Should be working fine but it can be tested with the public data: [https://cetaceans.ices.dk/Download/121c8af9-5914-419b-b843-d6e04a95d09c](https://cetaceans.ices.dk/Download/121c8af9-5914-419b-b843-d6e04a95d09c)

**Comment by neil-ices-dk** [comment]
@NikiClear to check that the fix is working please :)

**Comment by NikiClear** [comment]
> @NikiClear to check that the fix is working please :)

Tested and is working now
