### ISSUE TITLE
Review updated JCDP data use guidance document

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#301]
@neil-ices-dk 
To review the updated data use guidance document to check if there are any conflicts with existing ICES data policies. 

[JCDP_DataGuidance_PubV2.docx](https://github.com/ices-eg/WGJCDP-Cetaceans/files/13068846/JCDP_DataGuidance_PubV2.docx)

Once agreed, Niki C will update on the JCDP Hub

**Comment by neil-ices-dk** [comment]
@NikiClear i've edited the version and made comments, it was only when uploading it to Sharepoint i realised that the version you put here on Github is different to the version on Sharepoint. So there are 2 sharepoint documents to merge:

https://community.ices.dk/ExpertGroups/WGJCDP/2023%20Meeting%20Documents/04.%20Working%20documents/JCDP_DataGuidance_PubV2.docx (the original with the edits for licences)

the version with my comments/edits (which is based on the file in this thread but separate from the version on the link above)
https://community.ices.dk/ExpertGroups/WGJCDP/2023%20Meeting%20Documents/04.%20Working%20documents/JCDP_DataGuidance_PubV2-neil.docx

I think some of the comments/edits in my version are equivalent to the other updated version, generally the language and context needs to err towards guidance rather than obligation/policy

**Comment by NikiClear** [comment]
Hi Niel.

Thanks very much for your comments on this, I'll address these over the coming weeks and will circulate to the WG for final check before publishing on the Hub.

Many thanks,
Niki
________________________________

**Comment by NikiClear** [comment]
Edits reviewed and applied, document is in process of being re-published
