### ISSUE TITLE
As a Data user I want to be able to find other related relevant publications/data ..so that I can include additional supporting information in my work

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#44]
original id#41
@neil-ices-dk this sounds like links outside of the  iCES system - is it really 'in the ICES bag'?

**Comment by cmspinto** [comment]
Need clarification.

**Comment by neil-ices-dk** [comment]
@LynnHeeley this is not eniterly clear as a user story; i assume @GMDuncan added the label 'intheICESbag' as he was probably thinking of it from a metadata catalogue perspective. If that is what is meant, then i agree with him, otherwise i agree with you that it is outside the system and not in the bag

**Comment by GMDuncan** [comment]
Yes I believe this was determined to be fulfilled by the "Associated resources" elements that can currently already be added to metadata in the ICES Geonetwork.
